import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import CssBaseline from '@mui/material/CssBaseline';
import Header from '@/components/Header';
import AuthProvider from '@/context/AuthProvider';
import { ShopProvider } from '@/context/ShopProvider';
import { ToastContainer } from 'react-toastify';
import { CartProvider } from '@/context/CartProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'AudioPhile',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} relative`}>
        <CssBaseline />
        <AuthProvider>
          <ShopProvider>
            <CartProvider>
              <Header />
              {children}
            </CartProvider>
          </ShopProvider>
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
